import type { Journey } from '../data/schema'

export const napoleon: Journey = {
  id: 'napoleon',
  figure: 'Napoleon Bonaparte',
  title: 'The Rise and Fall of Napoleon',
  years: '1769–1821',
  color: '#e8b54a',
  intro: 'From a Corsican backwater to master of Europe and back to a rock in the South Atlantic — the most improbable arc in modern history.',
  stops: [
    { name: 'Ajaccio, Corsica', coords: { lat: 41.9192, lng: 8.7386 }, date: 'Aug 1769',
      story: 'Napoleone di Buonaparte is born into minor Corsican nobility, a year after France buys the island from Genoa. He grows up speaking Italian and resenting the French.' },
    { name: 'Brienne-le-Château', coords: { lat: 48.3922, lng: 4.5269 }, date: '1779',
      story: 'A nine-year-old scholarship boy at a French military school, mocked for his accent and his poverty. He buries himself in mathematics, history — and Plutarch.' },
    { name: 'Toulon', coords: { lat: 43.1242, lng: 5.928 }, date: 'Dec 1793',
      story: 'A 24-year-old artillery captain devises the plan that breaks the Anglo-Royalist siege. Promoted to brigadier general on the spot, he is suddenly a name in Paris.' },
    { name: 'Paris — 13 Vendémiaire', coords: { lat: 48.8666, lng: 2.3333 }, date: 'Oct 1795',
      story: 'Royalist crowds march on the Convention; Napoleon disperses them with cannon fire — the "whiff of grapeshot." The Republic now owes him.' },
    { name: 'Lodi', coords: { lat: 45.3138, lng: 9.5034 }, date: 'May 1796',
      story: 'Storming the bridge at Lodi during the Italian campaign, he leads from the front. His soldiers nickname him le petit caporal — and he begins to believe he is destined for more.' },
    { name: 'Cairo', coords: { lat: 30.0444, lng: 31.2357 }, date: 'Jul 1798',
      story: '"Soldiers, from the height of these pyramids, forty centuries look down upon you." The Egyptian expedition is a strategic failure and a propaganda triumph.',
      camera: { altitude: 0.12 } },
    { name: 'Saint-Cloud — 18 Brumaire', coords: { lat: 48.843, lng: 2.219 }, date: 'Nov 1799',
      story: 'A rushed, nearly botched coup makes him First Consul. The Revolution is over; at thirty, Napoleon rules France.' },
    { name: 'Notre-Dame de Paris', coords: { lat: 48.853, lng: 2.3499 }, date: 'Dec 1804',
      story: 'In front of the Pope, he takes the crown and places it on his own head. Emperor of the French — by his own hand.' },
    { name: 'Austerlitz', coords: { lat: 49.1281, lng: 16.7625 }, date: 'Dec 1805',
      story: 'His masterpiece. Outnumbered, he feigns weakness, surrenders the high ground, and destroys a Russo-Austrian army in a single morning.',
      battle: {
        name: 'Battle of Austerlitz', date: '2 December 1805',
        sides: { french: '#4d8fdb', coalition: '#c0392b' },
        strengths: { french: '73,000 men', coalition: '85,000 men' },
        // Camera stands SW of the field, looking NE across the Pratzen Heights.
        fieldAzimuth: 250,
        landmarks: [
          { name: 'Pratzen Heights', coords: { lat: 49.128, lng: 16.7625 }, kind: 'terrain' },
          { name: 'Satschan Ponds', coords: { lat: 49.08, lng: 16.73 }, kind: 'water' },
          { name: 'Sokolnitz', coords: { lat: 49.10, lng: 16.70 }, kind: 'settlement' },
          { name: 'Telnitz', coords: { lat: 49.09, lng: 16.71 }, kind: 'settlement' },
        ],
        phases: [
          { caption: 'The trap is set: Napoleon deliberately abandons the Pratzen Heights and weakens his right flank, inviting attack.',
            duration: 7,
            movements: [
              { side: 'french', style: 'feint', unit: 'Soult — IV Corps', path: [{ lat: 49.128, lng: 16.762 }, { lat: 49.13, lng: 16.69 }] },
            ] },
          { caption: 'The Allies take the bait: their columns pour south off the heights to envelop the French right, where Davout\'s corps arrives after a forced march to hold the line.',
            duration: 8,
            movements: [
              { side: 'coalition', style: 'advance', unit: 'Buxhöwden\'s columns', path: [{ lat: 49.128, lng: 16.762 }, { lat: 49.1, lng: 16.73 }, { lat: 49.09, lng: 16.705 }] },
              { side: 'french', style: 'advance', unit: 'Davout — III Corps', path: [{ lat: 49.06, lng: 16.65 }, { lat: 49.088, lng: 16.7 }] },
            ] },
          { caption: 'The masterstroke: as fog lifts under the "Sun of Austerlitz," Soult\'s corps storms the emptied Pratzen Heights and splits the Allied army in two.',
            duration: 7,
            movements: [
              { side: 'french', style: 'advance', unit: 'Soult — IV Corps', path: [{ lat: 49.125, lng: 16.7 }, { lat: 49.128, lng: 16.762 }] },
            ] },
          { caption: 'The rout: the French wheel south from the heights; the Allied left collapses and flees across the frozen Satschan ponds.',
            duration: 8,
            events: [
              { coords: { lat: 49.08, lng: 16.73 }, label: 'Allied troops flee across the frozen ponds' },
            ],
            movements: [
              { side: 'french', style: 'advance', unit: 'St. Hilaire & Vandamme', path: [{ lat: 49.128, lng: 16.762 }, { lat: 49.095, lng: 16.74 }] },
              { side: 'coalition', style: 'retreat', unit: 'Allied left wing', path: [{ lat: 49.09, lng: 16.72 }, { lat: 49.07, lng: 16.74 }] },
            ] },
        ],
      } },
    { name: 'Moscow', coords: { lat: 55.7558, lng: 37.6173 }, date: 'Sep 1812',
      story: 'He enters Moscow expecting surrender and finds it burning and empty. The retreat that follows destroys the Grande Armée — of 600,000 men, fewer than 100,000 return.',
      camera: { altitude: 0.2 } },
    { name: 'Leipzig', coords: { lat: 51.3397, lng: 12.3731 }, date: 'Oct 1813',
      story: 'The Battle of the Nations: outnumbered two to one by a united Europe, he is decisively beaten for the first time. France itself is now the battlefield.' },
    { name: 'Elba', coords: { lat: 42.8016, lng: 10.317 }, date: 'May 1814',
      story: 'Exiled as "Emperor" of a tiny Mediterranean island, he reorganizes its iron mines and roads — then, after ten months, slips past his jailers with a thousand men.' },
    { name: 'Waterloo', coords: { lat: 50.68, lng: 4.412 }, date: 'Jun 1815',
      story: 'The Hundred Days end in a sodden Belgian field. Wellington holds, Blücher arrives, and by nightfall the empire is finished forever.' },
    { name: 'Saint Helena', coords: { lat: -15.965, lng: -5.7089 }, date: '1815–1821',
      story: 'On a volcanic rock 2,000 km from anywhere, he dictates his memoirs and refights his battles for posterity. He dies in May 1821, aged 51.',
      camera: { altitude: 0.25 } },
  ],
}
