import type { Journey } from '../data/schema'

export const napoleon: Journey = {
  id: 'napoleon',
  figure: 'Napoleon Bonaparte',
  title: 'The Rise and Fall of Napoleon',
  years: '1769–1821',
  color: '#e8b54a',
  intro: 'From a Corsican backwater to master of Europe and back to a rock in the South Atlantic — the most improbable arc in modern history.',
  stops: [
    { name: 'Ajaccio, Corsica', coords: { lat: 41.9192, lng: 8.7386 }, date: 'Aug 1769',
      story: 'Napoleone di Buonaparte is born into minor Corsican nobility, a year after France buys the island from Genoa. He grows up speaking Italian and resenting the French.' },
    { name: 'Brienne-le-Château', coords: { lat: 48.3922, lng: 4.5269 }, date: '1779',
      story: 'A nine-year-old scholarship boy at a French military school, mocked for his accent and his poverty. He buries himself in mathematics, history — and Plutarch.' },
    { name: 'Toulon', coords: { lat: 43.1242, lng: 5.928 }, date: 'Dec 1793',
      story: 'A 24-year-old artillery captain devises the plan that breaks the Anglo-Royalist siege. Promoted to brigadier general on the spot, he is suddenly a name in Paris.' },
    { name: 'Paris — 13 Vendémiaire', coords: { lat: 48.8666, lng: 2.3333 }, date: 'Oct 1795',
      story: 'Royalist crowds march on the Convention; Napoleon disperses them with cannon fire — the "whiff of grapeshot." The Republic now owes him.' },
    { name: 'Lodi', coords: { lat: 45.3138, lng: 9.5034 }, date: 'May 1796',
      story: 'Storming the bridge at Lodi during the Italian campaign, he leads from the front. His soldiers nickname him le petit caporal — and he begins to believe he is destined for more.' },
    { name: 'Cairo', coords: { lat: 30.0444, lng: 31.2357 }, date: 'Jul 1798',
      story: '"Soldiers, from the height of these pyramids, forty centuries look down upon you." The Egyptian expedition is a strategic failure and a propaganda triumph.',
      camera: { altitude: 0.12 } },
    { name: 'Saint-Cloud — 18 Brumaire', coords: { lat: 48.843, lng: 2.219 }, date: 'Nov 1799',
      story: 'A rushed, nearly botched coup makes him First Consul. The Revolution is over; at thirty, Napoleon rules France.' },
    { name: 'Notre-Dame de Paris', coords: { lat: 48.853, lng: 2.3499 }, date: 'Dec 1804',
      story: 'In front of the Pope, he takes the crown and places it on his own head. Emperor of the French — by his own hand.' },
    { name: 'Austerlitz', coords: { lat: 49.1281, lng: 16.7625 }, date: 'Dec 1805',
      story: 'His masterpiece. Outnumbered, he feigns weakness, surrenders the high ground, and destroys a Russo-Austrian army in a single morning.',
      battle: {
        name: 'Battle of Austerlitz', date: '2 December 1805',
        sides: { french: '#4d8fdb', coalition: '#c0392b' },
        strengths: { french: '73,000 men', coalition: '85,000 men' },
        // Camera stands SW of the field, looking NE across the Pratzen Heights.
        fieldAzimuth: 250,
        areas: [
          {
            name: 'Pratzen Heights',
            kind: 'terrain',
            outline: [
              { lat: 49.115, lng: 16.740 },
              { lat: 49.118, lng: 16.758 },
              { lat: 49.128, lng: 16.775 },
              { lat: 49.138, lng: 16.785 },
              { lat: 49.142, lng: 16.770 },
              { lat: 49.135, lng: 16.748 },
              { lat: 49.122, lng: 16.735 },
            ],
          },
          {
            name: 'Satschan Ponds',
            kind: 'water',
            outline: [
              { lat: 49.072, lng: 16.720 },
              { lat: 49.075, lng: 16.735 },
              { lat: 49.082, lng: 16.742 },
              { lat: 49.088, lng: 16.738 },
              { lat: 49.085, lng: 16.722 },
              { lat: 49.078, lng: 16.715 },
            ],
          },
          {
            name: 'Goldbach Valley',
            kind: 'terrain',
            outline: [
              { lat: 49.090, lng: 16.698 },
              { lat: 49.098, lng: 16.705 },
              { lat: 49.110, lng: 16.712 },
              { lat: 49.118, lng: 16.718 },
              { lat: 49.115, lng: 16.708 },
              { lat: 49.105, lng: 16.700 },
              { lat: 49.095, lng: 16.692 },
            ],
          },
        ],
        phases: [
          { caption: 'The trap is set: Napoleon abandons the Pratzen Heights and strips his right flank — Lannes anchors the north, Murat\'s cavalry screens the Brünn road, Soult\'s corps lurks in the valley mist.',
            duration: 7,
            movements: [
              { side: 'french', style: 'feint', unit: 'Soult — IV Corps (feigned weakness)', path: [{ lat: 49.128, lng: 16.762 }, { lat: 49.118, lng: 16.720 }] },
              { side: 'french', style: 'feint', unit: 'Lannes — V Corps (north anchor)', path: [{ lat: 49.155, lng: 16.770 }, { lat: 49.158, lng: 16.778 }] },
              { side: 'french', style: 'feint', unit: 'Murat — Cavalry Reserve', path: [{ lat: 49.150, lng: 16.800 }, { lat: 49.148, lng: 16.810 }] },
            ] },
          { caption: 'The Allies take the bait: Buxhöwden\'s three columns pour south off the heights toward Sokolnitz and Telnitz; Davout\'s corps arrives after a 110 km forced march to hold the thinned French right.',
            duration: 8,
            movements: [
              { side: 'coalition', style: 'advance', unit: 'Buxhöwden — left-wing columns', path: [{ lat: 49.128, lng: 16.762 }, { lat: 49.100, lng: 16.730 }, { lat: 49.090, lng: 16.705 }] },
              { side: 'coalition', style: 'advance', unit: 'Kienmayer — advance guard', path: [{ lat: 49.115, lng: 16.745 }, { lat: 49.092, lng: 16.712 }] },
              { side: 'french', style: 'advance', unit: 'Davout — III Corps (forced march)', path: [{ lat: 49.060, lng: 16.650 }, { lat: 49.082, lng: 16.695 }, { lat: 49.088, lng: 16.700 }] },
            ] },
          { caption: 'The masterstroke: as fog burns off under the "Sun of Austerlitz," St. Hilaire and Vandamme\'s divisions storm the emptied Pratzen Heights; Bernadotte\'s corps secures the centre.',
            duration: 7,
            events: [
              { coords: { lat: 49.138, lng: 16.718 }, label: 'Napoleon watches from Zuran Hill as Soult storms the heights' },
            ],
            movements: [
              { side: 'french', style: 'advance', unit: 'St. Hilaire — division (south Pratzen)', path: [{ lat: 49.118, lng: 16.720 }, { lat: 49.124, lng: 16.748 }, { lat: 49.128, lng: 16.762 }] },
              { side: 'french', style: 'advance', unit: 'Vandamme — division (north Pratzen)', path: [{ lat: 49.122, lng: 16.725 }, { lat: 49.130, lng: 16.752 }, { lat: 49.132, lng: 16.768 }] },
              { side: 'french', style: 'advance', unit: 'Bernadotte — I Corps (centre link)', path: [{ lat: 49.135, lng: 16.730 }, { lat: 49.135, lng: 16.760 }] },
              { side: 'coalition', style: 'retreat', unit: 'Kollowrath — Allied centre', path: [{ lat: 49.128, lng: 16.762 }, { lat: 49.130, lng: 16.780 }] },
            ] },
          { caption: 'The rout: the French wheel south from the heights; the Russian Guard counter-attacks briefly before being driven back; the Allied left dissolves across the frozen Satschan ponds.',
            duration: 8,
            events: [
              { coords: { lat: 49.08, lng: 16.73 }, label: 'Allied troops flee across the frozen Satschan ponds' },
            ],
            movements: [
              { side: 'french', style: 'advance', unit: 'St. Hilaire & Vandamme (wheel south)', path: [{ lat: 49.128, lng: 16.762 }, { lat: 49.100, lng: 16.748 }, { lat: 49.092, lng: 16.738 }] },
              { side: 'coalition', style: 'advance', unit: 'Russian Imperial Guard (counter-attack)', path: [{ lat: 49.142, lng: 16.772 }, { lat: 49.132, lng: 16.762 }] },
              { side: 'french', style: 'advance', unit: 'Rapp — Guard cavalry (repulse the Guard)', path: [{ lat: 49.135, lng: 16.768 }, { lat: 49.140, lng: 16.774 }] },
              { side: 'coalition', style: 'retreat', unit: 'Allied left wing (Satschan flight)', path: [{ lat: 49.095, lng: 16.722 }, { lat: 49.075, lng: 16.738 }, { lat: 49.068, lng: 16.748 }] },
            ] },
        ],
      } },
    { name: 'Moscow', coords: { lat: 55.7558, lng: 37.6173 }, date: 'Sep 1812',
      story: 'He enters Moscow expecting surrender and finds it burning and empty. The retreat that follows destroys the Grande Armée — of 600,000 men, fewer than 100,000 return.',
      camera: { altitude: 0.2 } },
    { name: 'Leipzig', coords: { lat: 51.3397, lng: 12.3731 }, date: 'Oct 1813',
      story: 'The Battle of the Nations: outnumbered two to one by a united Europe, he is decisively beaten for the first time. France itself is now the battlefield.' },
    { name: 'Elba', coords: { lat: 42.8016, lng: 10.317 }, date: 'May 1814',
      story: 'Exiled as "Emperor" of a tiny Mediterranean island, he reorganizes its iron mines and roads — then, after ten months, slips past his jailers with a thousand men.' },
    { name: 'Waterloo', coords: { lat: 50.68, lng: 4.412 }, date: 'Jun 1815',
      story: 'The Hundred Days end in a sodden Belgian field. Wellington holds, Blücher arrives, and by nightfall the empire is finished forever.' },
    { name: 'Saint Helena', coords: { lat: -15.965, lng: -5.7089 }, date: '1815–1821',
      story: 'On a volcanic rock 2,000 km from anywhere, he dictates his memoirs and refights his battles for posterity. He dies in May 1821, aged 51.',
      camera: { altitude: 0.25 } },
  ],
}
